// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFHB3GJC-x7ar7ghdTSn04xbpA9tH0mk',
    appId: '1:123726403607:android:45a26e25d510d40d29e452',
    messagingSenderId: '123726403607',
    projectId: 'savi-ams',
    storageBucket: 'savi-ams.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2t6FEpzsLQ4YsjE7PBHs8d707QyQXCgo',
    appId: '1:123726403607:ios:33aae1de900eae6d29e452',
    messagingSenderId: '123726403607',
    projectId: 'savi-ams',
    storageBucket: 'savi-ams.firebasestorage.app',
    iosBundleId: 'com.savi.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2t6FEpzsLQ4YsjE7PBHs8d707QyQXCgo',
    appId: '1:123726403607:ios:20935aa7ddd0ef7c29e452',
    messagingSenderId: '123726403607',
    projectId: 'savi-ams',
    storageBucket: 'savi-ams.firebasestorage.app',
    iosBundleId: 'com.example.railWeld',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDyid-brN9BisVLUuD3rkdKQYrnUxQnVM',
    appId: '1:123726403607:web:962b2a6ad7bcd2db29e452',
    messagingSenderId: '123726403607',
    projectId: 'savi-ams',
    authDomain: 'savi-ams.firebaseapp.com',
    storageBucket: 'savi-ams.firebasestorage.app',
    measurementId: 'G-LHX9ZKMCJ1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDyid-brN9BisVLUuD3rkdKQYrnUxQnVM',
    appId: '1:123726403607:web:9ba12504d59ae1f329e452',
    messagingSenderId: '123726403607',
    projectId: 'savi-ams',
    authDomain: 'savi-ams.firebaseapp.com',
    storageBucket: 'savi-ams.firebasestorage.app',
    measurementId: 'G-D7QKLERC0S',
  );

}