// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApoXqI5QEauaYrLSBAReO-t9GlijXIpA0',
    appId: '1:722884734413:android:d02b4e7bd2e25952756884',
    messagingSenderId: '722884734413',
    projectId: 'mis-llh',
    storageBucket: 'mis-llh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8MHce1CmnFAwGWdRNfjSO-2hW5jd9xg',
    appId: '1:722884734413:ios:31ce2079647d9097756884',
    messagingSenderId: '722884734413',
    projectId: 'mis-llh',
    storageBucket: 'mis-llh.firebasestorage.app',
    iosBundleId: 'com.mis.llh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8MHce1CmnFAwGWdRNfjSO-2hW5jd9xg',
    appId: '1:722884734413:ios:3f0c936050e4d88a756884',
    messagingSenderId: '722884734413',
    projectId: 'mis-llh',
    storageBucket: 'mis-llh.firebasestorage.app',
    iosBundleId: 'com.example.railWeld',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPLfooQynqX-RfANYJZ1UJtjf7Yollz4',
    appId: '1:722884734413:web:7f87ca0b0c0d7f80756884',
    messagingSenderId: '722884734413',
    projectId: 'mis-llh',
    authDomain: 'mis-llh.firebaseapp.com',
    storageBucket: 'mis-llh.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADPLfooQynqX-RfANYJZ1UJtjf7Yollz4',
    appId: '1:722884734413:web:8d86468e52649666756884',
    messagingSenderId: '722884734413',
    projectId: 'mis-llh',
    authDomain: 'mis-llh.firebaseapp.com',
    storageBucket: 'mis-llh.firebasestorage.app',
  );

}